/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ApproveEditRecordRequest implements Serializable {

    @NotNull
    @JsonProperty("approvalPk")
    private Integer approvalPk;

    public Integer getApprovalPk() {
        return this.approvalPk;
    }

    public void setApprovalPk(Integer approvalPk) {
        this.approvalPk = approvalPk;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ApproveEditRecordRequest)) return false;
        final ApproveEditRecordRequest approveEditRecordRequest = (ApproveEditRecordRequest) o;
        return Objects.equals(getApprovalPk(), approveEditRecordRequest.getApprovalPk());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getApprovalPk());
    }
}
