/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Businessbusiness generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BUSINESSBUSINESS`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`BUSINESS_FK_CHILD`", "`BUSINESS_FK_PARENT`"})})
public class Businessbusiness implements Serializable {

    private Integer pk;
    private int businessFkChild;
    private int businessFkParent;
    private Integer businessRelationshipTypeFk;
    private Business businessByBusinessFkParent;
    private Business businessByBusinessFkChild;
    private Businessrelationshiptype businessrelationshiptype;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`PK`", nullable = false, scale = 0, precision = 10)
    public Integer getPk() {
        return this.pk;
    }

    public void setPk(Integer pk) {
        this.pk = pk;
    }

    @Column(name = "`BUSINESS_FK_CHILD`", nullable = false, scale = 0, precision = 10)
    public int getBusinessFkChild() {
        return this.businessFkChild;
    }

    public void setBusinessFkChild(int businessFkChild) {
        this.businessFkChild = businessFkChild;
    }

    @Column(name = "`BUSINESS_FK_PARENT`", nullable = false, scale = 0, precision = 10)
    public int getBusinessFkParent() {
        return this.businessFkParent;
    }

    public void setBusinessFkParent(int businessFkParent) {
        this.businessFkParent = businessFkParent;
    }

    @Column(name = "`BUSINESS_RELATIONSHIP_TYPE_FK`", nullable = true, scale = 0, precision = 10)
    public Integer getBusinessRelationshipTypeFk() {
        return this.businessRelationshipTypeFk;
    }

    public void setBusinessRelationshipTypeFk(Integer businessRelationshipTypeFk) {
        this.businessRelationshipTypeFk = businessRelationshipTypeFk;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BUSINESS_FK_PARENT`", referencedColumnName = "`PK`", insertable = false, updatable = false)
    public Business getBusinessByBusinessFkParent() {
        return this.businessByBusinessFkParent;
    }

    public void setBusinessByBusinessFkParent(Business businessByBusinessFkParent) {
        if(businessByBusinessFkParent != null) {
            this.businessFkParent = businessByBusinessFkParent.getPk();
        }

        this.businessByBusinessFkParent = businessByBusinessFkParent;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BUSINESS_FK_CHILD`", referencedColumnName = "`PK`", insertable = false, updatable = false)
    public Business getBusinessByBusinessFkChild() {
        return this.businessByBusinessFkChild;
    }

    public void setBusinessByBusinessFkChild(Business businessByBusinessFkChild) {
        if(businessByBusinessFkChild != null) {
            this.businessFkChild = businessByBusinessFkChild.getPk();
        }

        this.businessByBusinessFkChild = businessByBusinessFkChild;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BUSINESS_RELATIONSHIP_TYPE_FK`", referencedColumnName = "`PK`", insertable = false, updatable = false)
    public Businessrelationshiptype getBusinessrelationshiptype() {
        return this.businessrelationshiptype;
    }

    public void setBusinessrelationshiptype(Businessrelationshiptype businessrelationshiptype) {
        if(businessrelationshiptype != null) {
            this.businessRelationshipTypeFk = businessrelationshiptype.getPk();
        }

        this.businessrelationshiptype = businessrelationshiptype;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Businessbusiness)) return false;
        final Businessbusiness businessbusiness = (Businessbusiness) o;
        return Objects.equals(getPk(), businessbusiness.getPk());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPk());
    }
}

