/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Businessaddress;


/**
 * ServiceImpl object for domain model class Businessaddress.
 *
 * @see Businessaddress
 */
@Service("LSUC.BusinessaddressService")
public class BusinessaddressServiceImpl implements BusinessaddressService {

    private static final Logger LOGGER = LoggerFactory.getLogger(BusinessaddressServiceImpl.class);


    @Autowired
    @Qualifier("LSUC.BusinessaddressDao")
    private WMGenericDao<Businessaddress, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Businessaddress, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public Businessaddress create(Businessaddress businessaddress) {
        LOGGER.debug("Creating a new Businessaddress with information: {}", businessaddress);
        Businessaddress businessaddressCreated = this.wmGenericDao.create(businessaddress);
        return businessaddressCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Businessaddress getById(Integer businessaddressId) throws EntityNotFoundException {
        LOGGER.debug("Finding Businessaddress by id: {}", businessaddressId);
        Businessaddress businessaddress = this.wmGenericDao.findById(businessaddressId);
        if (businessaddress == null){
            LOGGER.debug("No Businessaddress found with id: {}", businessaddressId);
            throw new EntityNotFoundException(String.valueOf(businessaddressId));
        }
        return businessaddress;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Businessaddress findById(Integer businessaddressId) {
        LOGGER.debug("Finding Businessaddress by id: {}", businessaddressId);
        return this.wmGenericDao.findById(businessaddressId);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Businessaddress getByBusinessFkAndAddressTypeFk(Integer businessFk, Integer addressTypeFk) {
        Map<String, Object> businessFkAndAddressTypeFkMap = new HashMap<>();
        businessFkAndAddressTypeFkMap.put("businessFk", businessFk);
        businessFkAndAddressTypeFkMap.put("addressTypeFk", addressTypeFk);

        LOGGER.debug("Finding Businessaddress by unique keys: {}", businessFkAndAddressTypeFkMap);
        Businessaddress businessaddress = this.wmGenericDao.findByUniqueKey(businessFkAndAddressTypeFkMap);

        if (businessaddress == null){
            LOGGER.debug("No Businessaddress found with given unique key values: {}", businessFkAndAddressTypeFkMap);
            throw new EntityNotFoundException(String.valueOf(businessFkAndAddressTypeFkMap));
        }

        return businessaddress;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public Businessaddress update(Businessaddress businessaddress) throws EntityNotFoundException {
        LOGGER.debug("Updating Businessaddress with information: {}", businessaddress);
        this.wmGenericDao.update(businessaddress);

        Integer businessaddressId = businessaddress.getPk();

        return this.wmGenericDao.findById(businessaddressId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public Businessaddress delete(Integer businessaddressId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Businessaddress with id: {}", businessaddressId);
        Businessaddress deleted = this.wmGenericDao.findById(businessaddressId);
        if (deleted == null) {
            LOGGER.debug("No Businessaddress found with id: {}", businessaddressId);
            throw new EntityNotFoundException(String.valueOf(businessaddressId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<Businessaddress> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Businessaddresses");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Businessaddress> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Businessaddresses");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table Businessaddress to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

