/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Business;
import com.lsuc.lsuc.Businesslegaltype;

/**
 * Service object for domain model class {@link Businesslegaltype}.
 */
public interface BusinesslegaltypeService {

    /**
     * Creates a new Businesslegaltype. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Businesslegaltype if any.
     *
     * @param businesslegaltype Details of the Businesslegaltype to be created; value cannot be null.
     * @return The newly created Businesslegaltype.
     */
	Businesslegaltype create(Businesslegaltype businesslegaltype);


	/**
	 * Returns Businesslegaltype by given id if exists.
	 *
	 * @param businesslegaltypeId The id of the Businesslegaltype to get; value cannot be null.
	 * @return Businesslegaltype associated with the given businesslegaltypeId.
     * @throws EntityNotFoundException If no Businesslegaltype is found.
	 */
	Businesslegaltype getById(Integer businesslegaltypeId) throws EntityNotFoundException;

    /**
	 * Find and return the Businesslegaltype by given id if exists, returns null otherwise.
	 *
	 * @param businesslegaltypeId The id of the Businesslegaltype to get; value cannot be null.
	 * @return Businesslegaltype associated with the given businesslegaltypeId.
	 */
	Businesslegaltype findById(Integer businesslegaltypeId);

    /**
	 * Find and return the Businesslegaltype for given code  if exists.
	 *
	 * @param code value of code; value cannot be null.
	 * @return Businesslegaltype associated with the given inputs.
     * @throws EntityNotFoundException if no matching Businesslegaltype found.
	 */
    Businesslegaltype getByCode(String code)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Businesslegaltype. It replaces all fields of the existing Businesslegaltype with the given businesslegaltype.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Businesslegaltype if any.
     *
	 * @param businesslegaltype The details of the Businesslegaltype to be updated; value cannot be null.
	 * @return The updated Businesslegaltype.
	 * @throws EntityNotFoundException if no Businesslegaltype is found with given input.
	 */
	Businesslegaltype update(Businesslegaltype businesslegaltype) throws EntityNotFoundException;

    /**
	 * Deletes an existing Businesslegaltype with the given id.
	 *
	 * @param businesslegaltypeId The id of the Businesslegaltype to be deleted; value cannot be null.
	 * @return The deleted Businesslegaltype.
	 * @throws EntityNotFoundException if no Businesslegaltype found with the given id.
	 */
	Businesslegaltype delete(Integer businesslegaltypeId) throws EntityNotFoundException;

	/**
	 * Find all Businesslegaltypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Businesslegaltypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Businesslegaltype> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Businesslegaltypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Businesslegaltypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Businesslegaltype> findAll(String query, Pageable pageable);

    /**
	 * Exports all Businesslegaltypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Businesslegaltypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Businesslegaltype.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated businesses for given Businesslegaltype id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Business instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Business> findAssociatedBusinesses(Integer pk, Pageable pageable);

}

