/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Lawyer;


/**
 * ServiceImpl object for domain model class Lawyer.
 *
 * @see Lawyer
 */
@Service("LSUC.LawyerService")
public class LawyerServiceImpl implements LawyerService {

    private static final Logger LOGGER = LoggerFactory.getLogger(LawyerServiceImpl.class);


    @Autowired
    @Qualifier("LSUC.LawyerDao")
    private WMGenericDao<Lawyer, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Lawyer, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public Lawyer create(Lawyer lawyer) {
        LOGGER.debug("Creating a new Lawyer with information: {}", lawyer);
        Lawyer lawyerCreated = this.wmGenericDao.create(lawyer);
        return lawyerCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Lawyer getById(Integer lawyerId) throws EntityNotFoundException {
        LOGGER.debug("Finding Lawyer by id: {}", lawyerId);
        Lawyer lawyer = this.wmGenericDao.findById(lawyerId);
        if (lawyer == null){
            LOGGER.debug("No Lawyer found with id: {}", lawyerId);
            throw new EntityNotFoundException(String.valueOf(lawyerId));
        }
        return lawyer;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Lawyer findById(Integer lawyerId) {
        LOGGER.debug("Finding Lawyer by id: {}", lawyerId);
        return this.wmGenericDao.findById(lawyerId);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Lawyer getByLicenseeFk(Integer licenseeFk) {
        Map<String, Object> licenseeFkMap = new HashMap<>();
        licenseeFkMap.put("licenseeFk", licenseeFk);

        LOGGER.debug("Finding Lawyer by unique keys: {}", licenseeFkMap);
        Lawyer lawyer = this.wmGenericDao.findByUniqueKey(licenseeFkMap);

        if (lawyer == null){
            LOGGER.debug("No Lawyer found with given unique key values: {}", licenseeFkMap);
            throw new EntityNotFoundException(String.valueOf(licenseeFkMap));
        }

        return lawyer;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public Lawyer update(Lawyer lawyer) throws EntityNotFoundException {
        LOGGER.debug("Updating Lawyer with information: {}", lawyer);
        this.wmGenericDao.update(lawyer);

        Integer lawyerId = lawyer.getPk();

        return this.wmGenericDao.findById(lawyerId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public Lawyer delete(Integer lawyerId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Lawyer with id: {}", lawyerId);
        Lawyer deleted = this.wmGenericDao.findById(lawyerId);
        if (deleted == null) {
            LOGGER.debug("No Lawyer found with id: {}", lawyerId);
            throw new EntityNotFoundException(String.valueOf(lawyerId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<Lawyer> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Lawyers");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Lawyer> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Lawyers");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table Lawyer to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

