/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Licencetype;
import com.lsuc.lsuc.Licenseetype;

/**
 * Service object for domain model class {@link Licenseetype}.
 */
public interface LicenseetypeService {

    /**
     * Creates a new Licenseetype. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Licenseetype if any.
     *
     * @param licenseetype Details of the Licenseetype to be created; value cannot be null.
     * @return The newly created Licenseetype.
     */
	Licenseetype create(Licenseetype licenseetype);


	/**
	 * Returns Licenseetype by given id if exists.
	 *
	 * @param licenseetypeId The id of the Licenseetype to get; value cannot be null.
	 * @return Licenseetype associated with the given licenseetypeId.
     * @throws EntityNotFoundException If no Licenseetype is found.
	 */
	Licenseetype getById(Integer licenseetypeId) throws EntityNotFoundException;

    /**
	 * Find and return the Licenseetype by given id if exists, returns null otherwise.
	 *
	 * @param licenseetypeId The id of the Licenseetype to get; value cannot be null.
	 * @return Licenseetype associated with the given licenseetypeId.
	 */
	Licenseetype findById(Integer licenseetypeId);

    /**
	 * Find and return the Licenseetype for given code  if exists.
	 *
	 * @param code value of code; value cannot be null.
	 * @return Licenseetype associated with the given inputs.
     * @throws EntityNotFoundException if no matching Licenseetype found.
	 */
    Licenseetype getByCode(String code)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Licenseetype. It replaces all fields of the existing Licenseetype with the given licenseetype.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Licenseetype if any.
     *
	 * @param licenseetype The details of the Licenseetype to be updated; value cannot be null.
	 * @return The updated Licenseetype.
	 * @throws EntityNotFoundException if no Licenseetype is found with given input.
	 */
	Licenseetype update(Licenseetype licenseetype) throws EntityNotFoundException;

    /**
	 * Deletes an existing Licenseetype with the given id.
	 *
	 * @param licenseetypeId The id of the Licenseetype to be deleted; value cannot be null.
	 * @return The deleted Licenseetype.
	 * @throws EntityNotFoundException if no Licenseetype found with the given id.
	 */
	Licenseetype delete(Integer licenseetypeId) throws EntityNotFoundException;

	/**
	 * Find all Licenseetypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Licenseetypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Licenseetype> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Licenseetypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Licenseetypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Licenseetype> findAll(String query, Pageable pageable);

    /**
	 * Exports all Licenseetypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Licenseetypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Licenseetype.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated licencetypes for given Licenseetype id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Licencetype instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Licencetype> findAssociatedLicencetypes(Integer pk, Pageable pageable);

}

