/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Personphonecontact;


/**
 * ServiceImpl object for domain model class Personphonecontact.
 *
 * @see Personphonecontact
 */
@Service("LSUC.PersonphonecontactService")
public class PersonphonecontactServiceImpl implements PersonphonecontactService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PersonphonecontactServiceImpl.class);


    @Autowired
    @Qualifier("LSUC.PersonphonecontactDao")
    private WMGenericDao<Personphonecontact, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Personphonecontact, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public Personphonecontact create(Personphonecontact personphonecontact) {
        LOGGER.debug("Creating a new Personphonecontact with information: {}", personphonecontact);
        Personphonecontact personphonecontactCreated = this.wmGenericDao.create(personphonecontact);
        return personphonecontactCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Personphonecontact getById(Integer personphonecontactId) throws EntityNotFoundException {
        LOGGER.debug("Finding Personphonecontact by id: {}", personphonecontactId);
        Personphonecontact personphonecontact = this.wmGenericDao.findById(personphonecontactId);
        if (personphonecontact == null){
            LOGGER.debug("No Personphonecontact found with id: {}", personphonecontactId);
            throw new EntityNotFoundException(String.valueOf(personphonecontactId));
        }
        return personphonecontact;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Personphonecontact findById(Integer personphonecontactId) {
        LOGGER.debug("Finding Personphonecontact by id: {}", personphonecontactId);
        return this.wmGenericDao.findById(personphonecontactId);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Personphonecontact getByPersonFkAndPhonePurposeFkAndPhoneTypeFk(Integer personFk, Integer phonePurposeFk, Integer phoneTypeFk) {
        Map<String, Object> personFkAndPhonePurposeFkAndPhoneTypeFkMap = new HashMap<>();
        personFkAndPhonePurposeFkAndPhoneTypeFkMap.put("personFk", personFk);
        personFkAndPhonePurposeFkAndPhoneTypeFkMap.put("phonePurposeFk", phonePurposeFk);
        personFkAndPhonePurposeFkAndPhoneTypeFkMap.put("phoneTypeFk", phoneTypeFk);

        LOGGER.debug("Finding Personphonecontact by unique keys: {}", personFkAndPhonePurposeFkAndPhoneTypeFkMap);
        Personphonecontact personphonecontact = this.wmGenericDao.findByUniqueKey(personFkAndPhonePurposeFkAndPhoneTypeFkMap);

        if (personphonecontact == null){
            LOGGER.debug("No Personphonecontact found with given unique key values: {}", personFkAndPhonePurposeFkAndPhoneTypeFkMap);
            throw new EntityNotFoundException(String.valueOf(personFkAndPhonePurposeFkAndPhoneTypeFkMap));
        }

        return personphonecontact;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public Personphonecontact update(Personphonecontact personphonecontact) throws EntityNotFoundException {
        LOGGER.debug("Updating Personphonecontact with information: {}", personphonecontact);
        this.wmGenericDao.update(personphonecontact);

        Integer personphonecontactId = personphonecontact.getPk();

        return this.wmGenericDao.findById(personphonecontactId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public Personphonecontact delete(Integer personphonecontactId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Personphonecontact with id: {}", personphonecontactId);
        Personphonecontact deleted = this.wmGenericDao.findById(personphonecontactId);
        if (deleted == null) {
            LOGGER.debug("No Personphonecontact found with id: {}", personphonecontactId);
            throw new EntityNotFoundException(String.valueOf(personphonecontactId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<Personphonecontact> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Personphonecontacts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Personphonecontact> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Personphonecontacts");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table Personphonecontact to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

