/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Licenseepracticeineligibilitysubreason;
import com.lsuc.lsuc.Practiceinelgibilitysubreason;


/**
 * ServiceImpl object for domain model class Practiceinelgibilitysubreason.
 *
 * @see Practiceinelgibilitysubreason
 */
@Service("LSUC.PracticeinelgibilitysubreasonService")
public class PracticeinelgibilitysubreasonServiceImpl implements PracticeinelgibilitysubreasonService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PracticeinelgibilitysubreasonServiceImpl.class);

    @Autowired
	@Qualifier("LSUC.LicenseepracticeineligibilitysubreasonService")
	private LicenseepracticeineligibilitysubreasonService licenseepracticeineligibilitysubreasonService;

    @Autowired
    @Qualifier("LSUC.PracticeinelgibilitysubreasonDao")
    private WMGenericDao<Practiceinelgibilitysubreason, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Practiceinelgibilitysubreason, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public Practiceinelgibilitysubreason create(Practiceinelgibilitysubreason practiceinelgibilitysubreason) {
        LOGGER.debug("Creating a new Practiceinelgibilitysubreason with information: {}", practiceinelgibilitysubreason);
        Practiceinelgibilitysubreason practiceinelgibilitysubreasonCreated = this.wmGenericDao.create(practiceinelgibilitysubreason);
        if(practiceinelgibilitysubreasonCreated.getLicenseepracticeineligibilitysubreasons() != null) {
            for(Licenseepracticeineligibilitysubreason licenseepracticeineligibilitysubreason : practiceinelgibilitysubreasonCreated.getLicenseepracticeineligibilitysubreasons()) {
                licenseepracticeineligibilitysubreason.setPracticeinelgibilitysubreason(practiceinelgibilitysubreasonCreated);
                LOGGER.debug("Creating a new child Licenseepracticeineligibilitysubreason with information: {}", licenseepracticeineligibilitysubreason);
                licenseepracticeineligibilitysubreasonService.create(licenseepracticeineligibilitysubreason);
            }
        }
        return practiceinelgibilitysubreasonCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Practiceinelgibilitysubreason getById(Integer practiceinelgibilitysubreasonId) throws EntityNotFoundException {
        LOGGER.debug("Finding Practiceinelgibilitysubreason by id: {}", practiceinelgibilitysubreasonId);
        Practiceinelgibilitysubreason practiceinelgibilitysubreason = this.wmGenericDao.findById(practiceinelgibilitysubreasonId);
        if (practiceinelgibilitysubreason == null){
            LOGGER.debug("No Practiceinelgibilitysubreason found with id: {}", practiceinelgibilitysubreasonId);
            throw new EntityNotFoundException(String.valueOf(practiceinelgibilitysubreasonId));
        }
        return practiceinelgibilitysubreason;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Practiceinelgibilitysubreason findById(Integer practiceinelgibilitysubreasonId) {
        LOGGER.debug("Finding Practiceinelgibilitysubreason by id: {}", practiceinelgibilitysubreasonId);
        return this.wmGenericDao.findById(practiceinelgibilitysubreasonId);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Practiceinelgibilitysubreason getByCode(String code) {
        Map<String, Object> codeMap = new HashMap<>();
        codeMap.put("code", code);

        LOGGER.debug("Finding Practiceinelgibilitysubreason by unique keys: {}", codeMap);
        Practiceinelgibilitysubreason practiceinelgibilitysubreason = this.wmGenericDao.findByUniqueKey(codeMap);

        if (practiceinelgibilitysubreason == null){
            LOGGER.debug("No Practiceinelgibilitysubreason found with given unique key values: {}", codeMap);
            throw new EntityNotFoundException(String.valueOf(codeMap));
        }

        return practiceinelgibilitysubreason;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public Practiceinelgibilitysubreason update(Practiceinelgibilitysubreason practiceinelgibilitysubreason) throws EntityNotFoundException {
        LOGGER.debug("Updating Practiceinelgibilitysubreason with information: {}", practiceinelgibilitysubreason);
        this.wmGenericDao.update(practiceinelgibilitysubreason);

        Integer practiceinelgibilitysubreasonId = practiceinelgibilitysubreason.getPk();

        return this.wmGenericDao.findById(practiceinelgibilitysubreasonId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public Practiceinelgibilitysubreason delete(Integer practiceinelgibilitysubreasonId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Practiceinelgibilitysubreason with id: {}", practiceinelgibilitysubreasonId);
        Practiceinelgibilitysubreason deleted = this.wmGenericDao.findById(practiceinelgibilitysubreasonId);
        if (deleted == null) {
            LOGGER.debug("No Practiceinelgibilitysubreason found with id: {}", practiceinelgibilitysubreasonId);
            throw new EntityNotFoundException(String.valueOf(practiceinelgibilitysubreasonId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<Practiceinelgibilitysubreason> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Practiceinelgibilitysubreasons");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Practiceinelgibilitysubreason> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Practiceinelgibilitysubreasons");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table Practiceinelgibilitysubreason to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Licenseepracticeineligibilitysubreason> findAssociatedLicenseepracticeineligibilitysubreasons(Integer pk, Pageable pageable) {
        LOGGER.debug("Fetching all associated licenseepracticeineligibilitysubreasons");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("practiceinelgibilitysubreason.pk = '" + pk + "'");

        return licenseepracticeineligibilitysubreasonService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service LicenseepracticeineligibilitysubreasonService instance
	 */
	protected void setLicenseepracticeineligibilitysubreasonService(LicenseepracticeineligibilitysubreasonService service) {
        this.licenseepracticeineligibilitysubreasonService = service;
    }

}

