/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Classpraticegroup;
import com.lsuc.lsuc.Practicegroup;

/**
 * Service object for domain model class {@link Practicegroup}.
 */
public interface PracticegroupService {

    /**
     * Creates a new Practicegroup. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Practicegroup if any.
     *
     * @param practicegroup Details of the Practicegroup to be created; value cannot be null.
     * @return The newly created Practicegroup.
     */
	Practicegroup create(Practicegroup practicegroup);


	/**
	 * Returns Practicegroup by given id if exists.
	 *
	 * @param practicegroupId The id of the Practicegroup to get; value cannot be null.
	 * @return Practicegroup associated with the given practicegroupId.
     * @throws EntityNotFoundException If no Practicegroup is found.
	 */
	Practicegroup getById(Integer practicegroupId) throws EntityNotFoundException;

    /**
	 * Find and return the Practicegroup by given id if exists, returns null otherwise.
	 *
	 * @param practicegroupId The id of the Practicegroup to get; value cannot be null.
	 * @return Practicegroup associated with the given practicegroupId.
	 */
	Practicegroup findById(Integer practicegroupId);

    /**
	 * Find and return the Practicegroup for given code  andpracticeEligibilityFk  if exists.
	 *
	 * @param code value of code; value cannot be null.
	 * @param practiceEligibilityFk value of practiceEligibilityFk; value cannot be null.
	 * @return Practicegroup associated with the given inputs.
     * @throws EntityNotFoundException if no matching Practicegroup found.
	 */
    Practicegroup getByCodeAndPracticeEligibilityFk(String code, Integer practiceEligibilityFk)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Practicegroup. It replaces all fields of the existing Practicegroup with the given practicegroup.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Practicegroup if any.
     *
	 * @param practicegroup The details of the Practicegroup to be updated; value cannot be null.
	 * @return The updated Practicegroup.
	 * @throws EntityNotFoundException if no Practicegroup is found with given input.
	 */
	Practicegroup update(Practicegroup practicegroup) throws EntityNotFoundException;

    /**
	 * Deletes an existing Practicegroup with the given id.
	 *
	 * @param practicegroupId The id of the Practicegroup to be deleted; value cannot be null.
	 * @return The deleted Practicegroup.
	 * @throws EntityNotFoundException if no Practicegroup found with the given id.
	 */
	Practicegroup delete(Integer practicegroupId) throws EntityNotFoundException;

	/**
	 * Find all Practicegroups matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Practicegroups.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Practicegroup> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Practicegroups matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Practicegroups.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Practicegroup> findAll(String query, Pageable pageable);

    /**
	 * Exports all Practicegroups matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Practicegroups in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Practicegroup.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated classpraticegroups for given Practicegroup id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Classpraticegroup instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Classpraticegroup> findAssociatedClasspraticegroups(Integer pk, Pageable pageable);

}

