/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Businessaddress;
import com.lsuc.lsuc.Mailinglabel;
import com.lsuc.lsuc.Organizationalunitaddress;
import com.lsuc.lsuc.Personaddress;
import com.lsuc.lsuc.Province;

/**
 * Service object for domain model class {@link Province}.
 */
public interface ProvinceService {

    /**
     * Creates a new Province. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Province if any.
     *
     * @param province Details of the Province to be created; value cannot be null.
     * @return The newly created Province.
     */
	Province create(Province province);


	/**
	 * Returns Province by given id if exists.
	 *
	 * @param provinceId The id of the Province to get; value cannot be null.
	 * @return Province associated with the given provinceId.
     * @throws EntityNotFoundException If no Province is found.
	 */
	Province getById(Integer provinceId) throws EntityNotFoundException;

    /**
	 * Find and return the Province by given id if exists, returns null otherwise.
	 *
	 * @param provinceId The id of the Province to get; value cannot be null.
	 * @return Province associated with the given provinceId.
	 */
	Province findById(Integer provinceId);

    /**
	 * Find and return the Province for given code  if exists.
	 *
	 * @param code value of code; value cannot be null.
	 * @return Province associated with the given inputs.
     * @throws EntityNotFoundException if no matching Province found.
	 */
    Province getByCode(String code)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Province. It replaces all fields of the existing Province with the given province.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Province if any.
     *
	 * @param province The details of the Province to be updated; value cannot be null.
	 * @return The updated Province.
	 * @throws EntityNotFoundException if no Province is found with given input.
	 */
	Province update(Province province) throws EntityNotFoundException;

    /**
	 * Deletes an existing Province with the given id.
	 *
	 * @param provinceId The id of the Province to be deleted; value cannot be null.
	 * @return The deleted Province.
	 * @throws EntityNotFoundException if no Province found with the given id.
	 */
	Province delete(Integer provinceId) throws EntityNotFoundException;

	/**
	 * Find all Provinces matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Provinces.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Province> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Provinces matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Provinces.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Province> findAll(String query, Pageable pageable);

    /**
	 * Exports all Provinces matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Provinces in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Province.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated mailinglabels for given Province id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Mailinglabel instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Mailinglabel> findAssociatedMailinglabels(Integer pk, Pageable pageable);

    /*
     * Returns the associated businessaddresses for given Province id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Businessaddress instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Businessaddress> findAssociatedBusinessaddresses(Integer pk, Pageable pageable);

    /*
     * Returns the associated organizationalunitaddresses for given Province id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Organizationalunitaddress instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Organizationalunitaddress> findAssociatedOrganizationalunitaddresses(Integer pk, Pageable pageable);

    /*
     * Returns the associated personaddresses for given Province id.
     *
     * @param pk value of pk; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Personaddress instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Personaddress> findAssociatedPersonaddresses(Integer pk, Pageable pageable);

}

