/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.LicenseeAud;
import com.lsuc.lsuc.LicenseeclasspracticegroupAud;
import com.lsuc.lsuc.PersonAud;
import com.lsuc.lsuc.PersonaddressAud;
import com.lsuc.lsuc.Revinfo;

/**
 * Service object for domain model class {@link Revinfo}.
 */
public interface RevinfoService {

    /**
     * Creates a new Revinfo. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Revinfo if any.
     *
     * @param revinfo Details of the Revinfo to be created; value cannot be null.
     * @return The newly created Revinfo.
     */
	Revinfo create(Revinfo revinfo);


	/**
	 * Returns Revinfo by given id if exists.
	 *
	 * @param revinfoId The id of the Revinfo to get; value cannot be null.
	 * @return Revinfo associated with the given revinfoId.
     * @throws EntityNotFoundException If no Revinfo is found.
	 */
	Revinfo getById(Integer revinfoId) throws EntityNotFoundException;

    /**
	 * Find and return the Revinfo by given id if exists, returns null otherwise.
	 *
	 * @param revinfoId The id of the Revinfo to get; value cannot be null.
	 * @return Revinfo associated with the given revinfoId.
	 */
	Revinfo findById(Integer revinfoId);


	/**
	 * Updates the details of an existing Revinfo. It replaces all fields of the existing Revinfo with the given revinfo.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Revinfo if any.
     *
	 * @param revinfo The details of the Revinfo to be updated; value cannot be null.
	 * @return The updated Revinfo.
	 * @throws EntityNotFoundException if no Revinfo is found with given input.
	 */
	Revinfo update(Revinfo revinfo) throws EntityNotFoundException;

    /**
	 * Deletes an existing Revinfo with the given id.
	 *
	 * @param revinfoId The id of the Revinfo to be deleted; value cannot be null.
	 * @return The deleted Revinfo.
	 * @throws EntityNotFoundException if no Revinfo found with the given id.
	 */
	Revinfo delete(Integer revinfoId) throws EntityNotFoundException;

	/**
	 * Find all Revinfos matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Revinfos.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Revinfo> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Revinfos matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Revinfos.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Revinfo> findAll(String query, Pageable pageable);

    /**
	 * Exports all Revinfos matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Revinfos in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Revinfo.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated licenseeclasspracticegroupAuds for given Revinfo id.
     *
     * @param rev value of rev; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated LicenseeclasspracticegroupAud instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<LicenseeclasspracticegroupAud> findAssociatedLicenseeclasspracticegroupAuds(Integer rev, Pageable pageable);

    /*
     * Returns the associated personAuds for given Revinfo id.
     *
     * @param rev value of rev; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated PersonAud instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<PersonAud> findAssociatedPersonAuds(Integer rev, Pageable pageable);

    /*
     * Returns the associated personaddressAuds for given Revinfo id.
     *
     * @param rev value of rev; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated PersonaddressAud instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<PersonaddressAud> findAssociatedPersonaddressAuds(Integer rev, Pageable pageable);

    /*
     * Returns the associated licenseeAuds for given Revinfo id.
     *
     * @param rev value of rev; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated LicenseeAud instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<LicenseeAud> findAssociatedLicenseeAuds(Integer rev, Pageable pageable);

}

