/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Personrole;
import com.lsuc.lsuc.Role;


/**
 * ServiceImpl object for domain model class Role.
 *
 * @see Role
 */
@Service("LSUC.RoleService")
public class RoleServiceImpl implements RoleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(RoleServiceImpl.class);

    @Autowired
	@Qualifier("LSUC.PersonroleService")
	private PersonroleService personroleService;

    @Autowired
    @Qualifier("LSUC.RoleDao")
    private WMGenericDao<Role, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Role, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public Role create(Role role) {
        LOGGER.debug("Creating a new Role with information: {}", role);
        Role roleCreated = this.wmGenericDao.create(role);
        if(roleCreated.getPersonroles() != null) {
            for(Personrole personrole : roleCreated.getPersonroles()) {
                personrole.setRole(roleCreated);
                LOGGER.debug("Creating a new child Personrole with information: {}", personrole);
                personroleService.create(personrole);
            }
        }
        return roleCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Role getById(Integer roleId) throws EntityNotFoundException {
        LOGGER.debug("Finding Role by id: {}", roleId);
        Role role = this.wmGenericDao.findById(roleId);
        if (role == null){
            LOGGER.debug("No Role found with id: {}", roleId);
            throw new EntityNotFoundException(String.valueOf(roleId));
        }
        return role;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Role findById(Integer roleId) {
        LOGGER.debug("Finding Role by id: {}", roleId);
        return this.wmGenericDao.findById(roleId);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Role getByCode(String code) {
        Map<String, Object> codeMap = new HashMap<>();
        codeMap.put("code", code);

        LOGGER.debug("Finding Role by unique keys: {}", codeMap);
        Role role = this.wmGenericDao.findByUniqueKey(codeMap);

        if (role == null){
            LOGGER.debug("No Role found with given unique key values: {}", codeMap);
            throw new EntityNotFoundException(String.valueOf(codeMap));
        }

        return role;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public Role update(Role role) throws EntityNotFoundException {
        LOGGER.debug("Updating Role with information: {}", role);
        this.wmGenericDao.update(role);

        Integer roleId = role.getPk();

        return this.wmGenericDao.findById(roleId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public Role delete(Integer roleId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Role with id: {}", roleId);
        Role deleted = this.wmGenericDao.findById(roleId);
        if (deleted == null) {
            LOGGER.debug("No Role found with id: {}", roleId);
            throw new EntityNotFoundException(String.valueOf(roleId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<Role> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Role> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table Role to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<Personrole> findAssociatedPersonroles(Integer pk, Pageable pageable) {
        LOGGER.debug("Fetching all associated personroles");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("role.pk = '" + pk + "'");

        return personroleService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service PersonroleService instance
	 */
	protected void setPersonroleService(PersonroleService service) {
        this.personroleService = service;
    }

}

