/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.Userpreference;

/**
 * Service object for domain model class {@link Userpreference}.
 */
public interface UserpreferenceService {

    /**
     * Creates a new Userpreference. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Userpreference if any.
     *
     * @param userpreference Details of the Userpreference to be created; value cannot be null.
     * @return The newly created Userpreference.
     */
	Userpreference create(Userpreference userpreference);


	/**
	 * Returns Userpreference by given id if exists.
	 *
	 * @param userpreferenceId The id of the Userpreference to get; value cannot be null.
	 * @return Userpreference associated with the given userpreferenceId.
     * @throws EntityNotFoundException If no Userpreference is found.
	 */
	Userpreference getById(Integer userpreferenceId) throws EntityNotFoundException;

    /**
	 * Find and return the Userpreference by given id if exists, returns null otherwise.
	 *
	 * @param userpreferenceId The id of the Userpreference to get; value cannot be null.
	 * @return Userpreference associated with the given userpreferenceId.
	 */
	Userpreference findById(Integer userpreferenceId);

    /**
	 * Find and return the Userpreference for given userFk  anduserPreferenceTypeFk  if exists.
	 *
	 * @param userFk value of userFk; value cannot be null.
	 * @param userPreferenceTypeFk value of userPreferenceTypeFk; value cannot be null.
	 * @return Userpreference associated with the given inputs.
     * @throws EntityNotFoundException if no matching Userpreference found.
	 */
    Userpreference getByUserFkAndUserPreferenceTypeFk(Integer userFk, Integer userPreferenceTypeFk)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Userpreference. It replaces all fields of the existing Userpreference with the given userpreference.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Userpreference if any.
     *
	 * @param userpreference The details of the Userpreference to be updated; value cannot be null.
	 * @return The updated Userpreference.
	 * @throws EntityNotFoundException if no Userpreference is found with given input.
	 */
	Userpreference update(Userpreference userpreference) throws EntityNotFoundException;

    /**
	 * Deletes an existing Userpreference with the given id.
	 *
	 * @param userpreferenceId The id of the Userpreference to be deleted; value cannot be null.
	 * @return The deleted Userpreference.
	 * @throws EntityNotFoundException if no Userpreference found with the given id.
	 */
	Userpreference delete(Integer userpreferenceId) throws EntityNotFoundException;

	/**
	 * Find all Userpreferences matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Userpreferences.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Userpreference> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Userpreferences matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Userpreferences.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Userpreference> findAll(String query, Pageable pageable);

    /**
	 * Exports all Userpreferences matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Userpreferences in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Userpreference.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

